In [1]:
import pandas as pd
import numpy as np
import os

from utils.italian_provinces import italian_provinces

In [2]:
BASE_DIR = os.getcwd()
file_path_csv = os.path.join(BASE_DIR, "dataset", "dataset.csv")
file_path_xlsx = os.path.join(BASE_DIR, "dataset", "Corrispondenza-Ateco-2022-vs-NACE-Rev.-2.xlsx")

df_csv = pd.read_csv(file_path_csv, sep=";", encoding="latin-1")
df_xlsx = pd.read_excel(file_path_xlsx, sheet_name="NACE Rev. 2 vs Ateco 2022")

C:\Users\esaba\Desktop\Git hub projects\CapstoneProject-Logistic-S.p.a\.venv\Lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [3]:
df_csv.rename(columns={
    "Natura": "Nature",
    "Fatturato": "Revenue",
    "Dipendenti": "Employees",
    "Provincia": "Province"
}, inplace=True)

In [4]:
df_csv.loc[df_csv["Province"].notna(), ["City", "Region"]] = df_csv.loc[df_csv["Province"].notna(), "Province"].apply(
    lambda prov: pd.Series(italian_provinces.get(prov.strip().upper(), {"City": None, "Region": None}))
)

In [5]:
cols = list(df_csv.columns)
province_idx = cols.index("Province")
# rimuovo se esistono già
for col in ["City", "Region"]:
    if col in cols:
        cols.remove(col)
# inserisco
cols = cols[:province_idx+1] + ["City", "Region"] + cols[province_idx+1:]
df_csv = df_csv[cols]

In [6]:
# righe con Province presente ma City o Region mancanti
missing_city_region = df_csv[
    df_csv["Province"].notna() &
    (df_csv["City"].isna() | df_csv["Region"].isna())
]

print(f"Numero di righe non collegate: {len(missing_city_region)}")
missing_city_region[["Province", "City", "Region"]].head(20)  # mostra le prime 20

Numero di righe non collegate: 1

      Province City Region
13821       EE  NaN    NaN

In [7]:
df_csv.head()

,ATECO,ATECO_Desc,Nature,Revenue,Employees,Province,City,Region,M-35,M-34,...,M-9,M-8,M-7,M-6,M-5,M-4,M-3,M-2,M-1,M-0
0,G.47.71.00,Commercio al dettaglio di articoli di abbiglia...,1.a Impresa,93840,2,PA,Palermo,Sicilia,80,718,...,65919,58362,69779,62338,71332,54796,91169,104473,127672,139105
1,H.49.41.00,Trasporto di merci su strada,1.a Impresa,1242280,4,MB,Monza,Lombardia,44520,43793,...,78015,73822,83936,68864,107911,37607,100365,105866,84089,95330
2,G.47.91.30,Commercio al dettaglio di qualsiasi tipo di pr...,1.a Impresa,44451177,159,MI,Milano,Lombardia,65703,87812,...,35367,41628,60515,57786,85252,76067,86415,75573,101941,237050
3,N.77.40.00,CONCESSIONE DEI DIRITTI DI SFRUTTAMENTO DI PRO...,1.a Impresa,49918687,53,RM,Roma,Lazio,0,0,...,63667,74293,82637,80798,105440,74817,73151,76448,88819,85649
4,NaN,NaN,Altro / ND,0,0,NaN,NaN,NaN,240811,172007,...,47961,44201,53245,49897,81589,90283,74360,76854,62406,82700

In [8]:
df_csv[df_csv['Province'] == 'TI']

,ATECO,ATECO_Desc,Nature,Revenue,Employees,Province,City,Region,M-35,M-34,...,M-9,M-8,M-7,M-6,M-5,M-4,M-3,M-2,M-1,M-0
120,H.53.20.00,Altre attività postali e di corriere senza obb...,1.a Impresa,0,0,TI,Ticino,Switzerland,6878,6741,...,15573,12473,14093,10099,25744,7769,12642,13360,15445,21086

In [9]:
df_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 20436 entries, 0 to 20435
Data columns (total 44 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ATECO       20049 non-null  str
 1   ATECO_Desc  20049 non-null  str
 2   Nature      20436 non-null  str
 3   Revenue     20436 non-null  int64
 4   Employees   20436 non-null  int64
 5   Province    16936 non-null  str
 6   City        16935 non-null  str
 7   Region      16935 non-null  str
 8   M-35        20436 non-null  int64
 9   M-34        20436 non-null  int64
 10  M-33        20436 non-null  int64
 11  M-32        20436 non-null  int64
 12  M-31        20436 non-null  int64
 13  M-30        20436 non-null  int64
 14  M-29        20436 non-null  int64
 15  M-28        20436 non-null  int64
 16  M-27        20436 non-null  int64
 17  M-26        20436 non-null  int64
 18  M-25        20436 non-null  int64
 19  M-24        20436 non-null  int64
 20  M-23        20436 non-null  int64
 21  M-22        20436 non-null  int64
 22  M-21        20436 non-null  int64
 23  M-20        20436 non-null  int64
 24  M-19        20436 non-null  int64
 25  M-18        20436 non-null  int64
 26  M-17        20436 non-null  int64
 27  M-16        20436 non-null  int64
 28  M-15        20436 non-null  int64
 29  M-14        20436 non-null  int64
 30  M-13        20436 non-null  int64
 31  M-12        20436 non-null  int64
 32  M-11        20436 non-null  int64
 33  M-10        20436 non-null  int64
 34  M-9         20436 non-null  int64
 35  M-8         20436 non-null  int64
 36  M-7         20436 non-null  int64
 37  M-6         20436 non-null  int64
 38  M-5         20436 non-null  int64
 39  M-4         20436 non-null  int64
 40  M-3         20436 non-null  int64
 41  M-2         20436 non-null  int64
 42  M-1         20436 non-null  int64
 43  M-0         20436 non-null  int64
dtypes: int64(38), str(6)
memory usage: 6.9 MB

In [10]:
df_csv.describe()

,Revenue,Employees,M-35,M-34,M-33,M-32,M-31,M-30,M-29,M-28,...,M-9,M-8,M-7,M-6,M-5,M-4,M-3,M-2,M-1,M-0
count,2.043600e+04,20436.000000,2.043600e+04,2.043600e+04,2.043600e+04,20436.000000,20436.000000,20436.000000,20436.000000,20436.000000,...,20436.000000,20436.000000,20436.000000,20436.000000,20436.000000,20436.000000,20436.000000,20436.000000,20436.000000,20436.000000
mean,3.814559e+06,21.343120,4.844733e+02,4.754634e+02,5.199870e+02,431.743639,512.020894,424.876737,416.414954,321.661382,...,457.326140,455.670288,500.878890,449.031024,505.828929,325.216432,481.346790,547.444852,566.194510,614.266246
std,7.999604e+06,159.474594,8.178875e+03,9.540971e+03,8.653320e+03,4609.221206,8214.296953,3271.023212,3434.653672,2600.718541,...,2831.406553,2928.458317,3156.428343,2835.448864,3409.271805,2461.087865,3160.556412,3484.641725,3882.217904,4626.793992
min,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,-98444.000000,-192.000000,-163.000000,-115.000000,...,0.000000,0.000000,0.000000,-62.000000,0.000000,0.000000,0.000000,-343.000000,0.000000,0.000000
25%,0.000000e+00,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,5.217480e+05,4.000000,6.000000e+00,7.000000e+00,8.000000e+00,5.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,3.275647e+06,15.000000,1.122500e+02,1.210000e+02,1.360000e+02,115.000000,117.000000,101.000000,108.000000,62.250000,...,95.000000,90.000000,104.000000,90.000000,95.000000,41.000000,87.000000,106.000000,98.000000,82.000000
max,5.792155e+07,19555.000000,1.069153e+06,1.301728e+06,1.159983e+06,508106.000000,862767.000000,218053.000000,247967.000000,178321.000000,...,80319.000000,121988.000000,134135.000000,88731.000000,144431.000000,96789.000000,139446.000000,117746.000000,198993.000000,251130.000000

In [11]:
df_csv.isnull().mean() * 100

ATECO          1.893717
ATECO_Desc     1.893717
Nature         0.000000
Revenue        0.000000
Employees      0.000000
Province      17.126639
City          17.131533
Region        17.131533
M-35           0.000000
M-34           0.000000
M-33           0.000000
M-32           0.000000
M-31           0.000000
M-30           0.000000
M-29           0.000000
M-28           0.000000
M-27           0.000000
M-26           0.000000
M-25           0.000000
M-24           0.000000
M-23           0.000000
M-22           0.000000
M-21           0.000000
M-20           0.000000
M-19           0.000000
M-18           0.000000
M-17           0.000000
M-16           0.000000
M-15           0.000000
M-14           0.000000
M-13           0.000000
M-12           0.000000
M-11           0.000000
M-10           0.000000
M-9            0.000000
M-8            0.000000
M-7            0.000000
M-6            0.000000
M-5            0.000000
M-4            0.000000
M-3            0.000000
M-2            0.000000
M-1            0.000000
M-0            0.000000
dtype: float64

In [12]:
df_csv = df_csv.dropna()

cols = [f"M-{i}" for i in range(36)]

df_csv = df_csv[df_csv[cols].sum(axis=1) != 0]

In [13]:
df_csv['ATECO_norm'] = df_csv['ATECO'].str[2:]
df_csv['ATECO_Desc'] = (
    df_csv['ATECO_Desc']
    .str.lower()
    .str.replace(r'[^\w\s]', '', regex=True)
    .str.strip()
)

In [14]:
df_xlsx.columns = ['NACE', 'NACE_Desc', 'ATECO_2007', 'ATECO_2007_Desc']
df_xlsx['ATECO_2007_Desc'] = (
    df_xlsx['ATECO_2007_Desc']
    .str.lower()
    .str.replace(r'[^\w\s]', '', regex=True)
    .str.strip()
)

In [15]:
# 1. Primo tentativo: Join su ATECO_norm
df = df_csv.merge(
    df_xlsx,
    how="left",
    left_on="ATECO_norm",
    right_on="ATECO_2007"
)

df_2 = df_csv.merge(
    df_xlsx,
    how="left",
    left_on="ATECO_Desc",
    right_on="ATECO_2007_Desc",
    suffixes=('', '_backup')
)

df['NACE'] = df['NACE'].fillna(df_2['NACE'])
df['NACE_Desc'] = df['NACE_Desc'].fillna(df_2['NACE_Desc'])
df['ATECO_2007'] = df['ATECO_2007'].fillna(df_2['ATECO_2007'])
df['ATECO_2007_Desc'] = df['ATECO_2007_Desc'].fillna(df_2['ATECO_2007_Desc'])

In [16]:
# righe con Province presente ma City o Region mancanti
missing_NACE = df[
    df["NACE"].isna()
]

print(f"Numero di righe non collegate: {len(missing_NACE)}")
missing_NACE[["ATECO", "ATECO_Desc"]].head(20)  # mostra le prime 20

Numero di righe non collegate: 25

            ATECO                                         ATECO_Desc
3265   S.94.00.00             attività di organizzazioni associative
3682   C.25.73.10  fabbricazione di utensileria ad azionamento ma...
7495   N.79.10.00  attività delle agenzie di viaggio e dei tour o...
7617   C.24.50.00                                           fonderie
8645   G.46.60.00  commercio allingrosso di altri macchinari attr...
8800     O.8411C1                    governo e organi costituzionali
9142   C.27.40.00  fabbricazione di apparecchiature per illuminaz...
10282  C.28.49.00           fabbricazione di altre macchine utensili
11431  K.66.20.00  attività ausiliarie delle assicurazioni e dei ...
11459  C.21.00.00  fabbricazione di prodotti farmaceutici di base...
11650  C.25.73.10  fabbricazione di utensileria ad azionamento ma...
11837  G.47.71.00  commercio al dettaglio di articoli di abbiglia...
12128  C.15.20.00                         fabbricazione di calzature
13047  C.31.09.00                      fabbricazione di altri mobili
13678  G.46.17.00  intermediari del commercio di prodotti aliment...
14068  M.74.90.10                                 consulenza agraria
14223  G.46.69.00  commercio allingrosso di altri macchinari e at...
14483  Q.86.10.00                                servizi ospedalieri
14764    O.8411L1                                             comuni
14799    O.8411L1                                             comuni

In [17]:
cols_to_drop = ['ATECO', 'ATECO_Desc', 'ATECO_2007', 'ATECO_2007_Desc', 'ATECO_norm', 'Nature']

df = df.drop(columns=cols_to_drop)

cols = df.columns.tolist()
last_two = cols[-2:]
rest = cols[:-2]
new_order = last_two + rest
df = df[new_order]

In [18]:
df.head()

,NACE,NACE_Desc,Revenue,Employees,Province,City,Region,M-35,M-34,M-33,...,M-9,M-8,M-7,M-6,M-5,M-4,M-3,M-2,M-1,M-0
0,47.71,Retail sale of clothing in specialised stores,93840,2,PA,Palermo,Sicilia,80,718,3888,...,65919,58362,69779,62338,71332,54796,91169,104473,127672,139105
1,49.41,Freight transport by road,1242280,4,MB,Monza,Lombardia,44520,43793,54545,...,78015,73822,83936,68864,107911,37607,100365,105866,84089,95330
2,47.91,Retail sale via mail order houses or via Internet,44451177,159,MI,Milano,Lombardia,65703,87812,65768,...,35367,41628,60515,57786,85252,76067,86415,75573,101941,237050
3,77.40,Leasing of intellectual property and similar p...,49918687,53,RM,Roma,Lazio,0,0,0,...,63667,74293,82637,80798,105440,74817,73151,76448,88819,85649
4,62.01,Computer programming activities,7115458,18,MI,Milano,Lombardia,47372,38998,32265,...,62883,58357,66783,64001,96385,57581,58713,72002,76832,76719